welcome_user_task:
  description: >
    Welcome {username} to their {target_language} learning session. They are at {level} level 
    and speak {native_language} natively. Create a warm, encouraging welcome message that sets 
    a positive tone for learning and asks if they're ready to begin or continue their studies.
  expected_output: >
    A personalized, encouraging welcome message that makes {username} feel comfortable and 
    motivated to start learning {target_language}.
  agent: conversational_agent

get_next_lesson_task:
  description: >
    Based on {username}'s current progress (lesson {current_lesson}, {success_rate}% success rate), 
    generate the next appropriate {target_language} phrase for a {level} level {native_language} 
    speaker. Avoid proper nouns. Include the target phrase, correct IPA transcription, difficulty 
    level, and learning objectives. Consider their native language background for targeted instruction.
  expected_output: >
    A structured lesson containing: target phrase (avoiding proper nouns), correct IPA transcription, 
    difficulty level, learning objectives, and specific pronunciation focus areas for {native_language} 
    speakers learning {target_language}.
  agent: curriculum_agent

analyze_pronunciation_task:
  description: >
    Analyze {username}'s pronunciation attempt using advanced IPA and probability analysis. 
    Compare user IPA '{user_ipa}' against correct IPA for target phrase '{target_phrase}'. 
    Use top-K phone probabilities {topk_results} to identify near-misses and confusion patterns. 
    Consider their {native_language} background for targeted feedback. Provide nuanced analysis 
    like "You nearly said X but may have confused it with Y" based on probability data. 
    Infer word boundaries from the flat IPA string if needed.
  expected_output: >
    Detailed pronunciation analysis with: pass/fail status, specific feedback, identified 
    pronunciation issues, improvement suggestions, and probability-based insights explaining 
    near-misses and alternative pronunciations detected.
  agent: pronunciation_coach_agent

present_lesson_task:
  description: >
    Present this curriculum step to {username} in a friendly, encouraging manner: '{curriculum_result}'. 
    Convert the structured lesson data into natural, supportive chat message format. Make it clear 
    what they need to do and keep them motivated to practice the pronunciation.
  expected_output: >
    A friendly, conversational presentation of the lesson with clear instructions for {username}, 
    formatted as natural dialogue that encourages practice and engagement.
  agent: conversational_agent

present_feedback_task:
  description: >
    Present this pronunciation analysis to {username} in an encouraging way: '{analysis_result}'. 
    Convert the technical feedback into supportive, actionable guidance. They have attempted this 
    phrase {current_phrase_attempts} times. If they've tried 3+ times ({should_offer_to_advance}), 
    offer them the choice to move on to the next phrase while being encouraging about their effort. 
    Decide whether they should retry, move on, or let them choose. Maintain motivation and celebrate 
    any progress made.
  expected_output: >
    Encouraging, personalized feedback message with clear next steps (retry, advance, or user choice), 
    formatted as supportive conversation that keeps {username} motivated. If offering to advance after 
    retries, phrase it positively like "You've given this great effort! Would you like to try once 
    more or move on to something new?"
  agent: conversational_agent